### ISSUE TITLE
discuss

### ISSUE THREAD

**Issue by andyComeOn** [neversaysoso/superhero#1]
一、clone项目之后，进入目录，执行npm install , 出现这个

![image](https://user-images.githubusercontent.com/19949116/33195649-6fe45a28-d114-11e7-9637-84b52fa154ae.png)。很是疑问。怎么会报这个错误？

###

二、安装npm i thor-x --save

三、运行npm run dev 出现如下

 ![image](https://user-images.githubusercontent.com/19949116/33195624-3265dd70-d114-11e7-8849-d8215c61745d.png)。

**Comment by neversaysoso** [comment]
直接用npm run dev运行就可以了 这个项目里不需要安装。组件安装在你实际项目里使用。

**Comment by andyComeOn** [comment]
@neversaysoso  这样一定会报错我感觉（我试了err），你没有依赖，你的vue从哪里来啊，兄弟。

**Comment by neversaysoso** [comment]
更下新代码

**Comment by andyComeOn** [comment]
@neversaysoso  你试一试自己在一个本地目录下clone一下，能npm run dev能跑起来吗？兄弟

**Comment by neversaysoso** [comment]
没问题，建议更新下版本
